language: ruby
bundler_args: --without manual_development
matrix:
  include:
    - rvm: 1.9.3
      env: RAILS_VERSION_SPEC=4.2.0
    - rvm: 2.2.1
      env: RAILS_VERSION_SPEC=4.2.0
    - rvm: 2.3.1
      env: RAILS_VERSION_SPEC=4.2.0
    - rvm: 2.3.1
      env: RAILS_VERSION_SPEC=5.0.0
    - rvm: jruby-19mode
      env: RAILS_VERSION_SPEC=4.2.0
    - rvm: jruby-9.1.5.0
      env: RAILS_VERSION_SPEC=4.2.0
    - rvm: jruby-9.1.5.0
      env: RAILS_VERSION_SPEC=5.0.0
  allow_failures:
    # SQLite3, JRuby, and Rails5 seem to be not happy
    - rvm: jruby-9.1.5.0
      env: RAILS_VERSION_SPEC=5.0.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
before_install:
  - gem install bundler
# use new faster travis infrastructure
sudo: false
# which let's us do caching
cache: bundler
