language: ruby
bundler_args: --without manual_development
rvm:
  #- 1.8.7
  #- 1.9.2
  - 1.9.3
  - 2.2.1
  - 2.3.1
  #- jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  #- rbx-18mode
  #- rbx-19mode
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
before_install:
  - gem install bundler
# use new faster travis infrastructure
sudo: false
# which let's us do caching
cache: bundler
